version: "3.8"

networks:
  webapp:

services:
  php-fpm:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./docker/php
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/app